server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/sifipro_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:83Dakota77}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.auth.jwt.secret=${APP_JWT_SECRET:z9BqL4xV2mR8pW6jN3cK7hT5fD1sY0gH4vM2kF9bD6nJ3rP8tC}
app.auth.jwt.expiration-ms=86400000

