-- Baseline schema migration for SIFIPRO.
--
-- Captures the schema exactly as it existed in the sifipro_db development database
-- right before Flyway was enabled, i.e. everything Hibernate (ddl-auto=update) had
-- already created up to and including the "version" (@Version) and "created_by"
-- (audit) columns. This is a snapshot, not a redesigned/idealized schema — from this
-- point forward, schema changes must be added as new Flyway migrations instead of
-- relying on ddl-auto.
--
-- Generated with:
--   pg_dump --schema-only --no-owner --no-privileges --no-tablespaces -x sifipro_db
--
-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: app_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    email character varying(150) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    tenant_id bigint NOT NULL,
    CONSTRAINT app_users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'STAFF'::character varying])::text[])))
);


--
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    email character varying(150) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone character varying(30),
    points_balance numeric(12,4) NOT NULL,
    tenant_id bigint NOT NULL,
    version bigint
);


--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: points_movements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.points_movements (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    description character varying(300),
    points numeric(12,4) NOT NULL,
    reference_id bigint NOT NULL,
    reference_type character varying(50) NOT NULL,
    type character varying(20) NOT NULL,
    customer_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    program_config_id bigint NOT NULL,
    created_by bigint,
    CONSTRAINT points_movements_type_check CHECK (((type)::text = ANY ((ARRAY['EARN'::character varying, 'REDEEM'::character varying, 'ADJUSTMENT'::character varying, 'EXPIRE'::character varying])::text[])))
);


--
-- Name: points_movements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.points_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.points_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: program_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.program_config (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    minimum_purchase_amount numeric(12,2) NOT NULL,
    points_per_dollar numeric(12,4) NOT NULL,
    program_name character varying(100) NOT NULL,
    tenant_id bigint NOT NULL
);


--
-- Name: program_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.program_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.program_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_transactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    amount numeric(12,2) NOT NULL,
    description character varying(300),
    points_earned numeric(12,4) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    program_config_id bigint NOT NULL,
    created_by bigint
);


--
-- Name: purchase_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchase_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: redemptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.redemptions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    notes character varying(300),
    points_used numeric(12,4) NOT NULL,
    redemption_date timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    customer_id bigint NOT NULL,
    reward_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    program_config_id bigint NOT NULL,
    created_by bigint,
    CONSTRAINT redemptions_status_check CHECK (((status)::text = ANY ((ARRAY['COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: redemptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.redemptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.redemptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rewards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rewards (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    description character varying(500),
    name character varying(120) NOT NULL,
    required_points numeric(12,4) NOT NULL,
    stock integer NOT NULL,
    tenant_id bigint NOT NULL,
    program_config_id bigint NOT NULL,
    image_url character varying(500),
    version bigint
);


--
-- Name: rewards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rewards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rewards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenants (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    name character varying(150) NOT NULL,
    code character varying(100) NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: tenants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tenants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tenants_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tenants_id_seq OWNED BY public.tenants.id;


--
-- Name: tenants id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants ALTER COLUMN id SET DEFAULT nextval('public.tenants_id_seq'::regclass);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: points_movements points_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_movements
    ADD CONSTRAINT points_movements_pkey PRIMARY KEY (id);


--
-- Name: program_config program_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program_config
    ADD CONSTRAINT program_config_pkey PRIMARY KEY (id);


--
-- Name: purchase_transactions purchase_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_transactions
    ADD CONSTRAINT purchase_transactions_pkey PRIMARY KEY (id);


--
-- Name: redemptions redemptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.redemptions
    ADD CONSTRAINT redemptions_pkey PRIMARY KEY (id);


--
-- Name: rewards rewards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rewards
    ADD CONSTRAINT rewards_pkey PRIMARY KEY (id);


--
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);


--
-- Name: app_users uk4vj92ux8a2eehds1mdvmks473; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT uk4vj92ux8a2eehds1mdvmks473 UNIQUE (email);


--
-- Name: tenants uk_tenants_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT uk_tenants_code UNIQUE (code);


--
-- Name: customers ukrfbvkrffamfql7cjmen8v976v; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukrfbvkrffamfql7cjmen8v976v UNIQUE (email);


--
-- Name: idx_app_users_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_users_tenant_id ON public.app_users USING btree (tenant_id);


--
-- Name: idx_customers_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customers_tenant_id ON public.customers USING btree (tenant_id);


--
-- Name: idx_points_movements_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_points_movements_tenant_id ON public.points_movements USING btree (tenant_id);


--
-- Name: idx_points_movements_tenant_program_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_points_movements_tenant_program_id ON public.points_movements USING btree (tenant_id, program_config_id);


--
-- Name: idx_program_config_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_program_config_tenant_id ON public.program_config USING btree (tenant_id);


--
-- Name: idx_purchase_transactions_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_purchase_transactions_tenant_id ON public.purchase_transactions USING btree (tenant_id);


--
-- Name: idx_purchase_transactions_tenant_program_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_purchase_transactions_tenant_program_id ON public.purchase_transactions USING btree (tenant_id, program_config_id);


--
-- Name: idx_redemptions_customer_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_redemptions_customer_tenant_id ON public.redemptions USING btree (customer_id, tenant_id);


--
-- Name: idx_redemptions_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_redemptions_tenant_id ON public.redemptions USING btree (tenant_id);


--
-- Name: idx_redemptions_tenant_program_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_redemptions_tenant_program_id ON public.redemptions USING btree (tenant_id, program_config_id);


--
-- Name: idx_rewards_program_config_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rewards_program_config_id ON public.rewards USING btree (program_config_id);


--
-- Name: idx_rewards_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rewards_tenant_id ON public.rewards USING btree (tenant_id);


--
-- Name: uk_customers_tenant_email_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_customers_tenant_email_lower ON public.customers USING btree (tenant_id, lower((email)::text));


--
-- Name: uk_program_config_tenant_program_name_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_program_config_tenant_program_name_lower ON public.program_config USING btree (tenant_id, lower((program_name)::text));


--
-- Name: uk_rewards_program_name_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_rewards_program_name_lower ON public.rewards USING btree (program_config_id, lower((name)::text));


--
-- Name: redemptions fk2nkje70427p6seys7h769avpf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.redemptions
    ADD CONSTRAINT fk2nkje70427p6seys7h769avpf FOREIGN KEY (reward_id) REFERENCES public.rewards(id);


--
-- Name: redemptions fk93cae0m5re1256tc2h7gntt7v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.redemptions
    ADD CONSTRAINT fk93cae0m5re1256tc2h7gntt7v FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: app_users fk_app_users_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT fk_app_users_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: customers fk_customers_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT fk_customers_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: points_movements fk_points_movements_program_config; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_movements
    ADD CONSTRAINT fk_points_movements_program_config FOREIGN KEY (program_config_id) REFERENCES public.program_config(id);


--
-- Name: points_movements fk_points_movements_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_movements
    ADD CONSTRAINT fk_points_movements_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: program_config fk_program_config_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program_config
    ADD CONSTRAINT fk_program_config_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: purchase_transactions fk_purchase_transactions_program_config; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_transactions
    ADD CONSTRAINT fk_purchase_transactions_program_config FOREIGN KEY (program_config_id) REFERENCES public.program_config(id);


--
-- Name: purchase_transactions fk_purchase_transactions_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_transactions
    ADD CONSTRAINT fk_purchase_transactions_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: redemptions fk_redemptions_program_config; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.redemptions
    ADD CONSTRAINT fk_redemptions_program_config FOREIGN KEY (program_config_id) REFERENCES public.program_config(id);


--
-- Name: redemptions fk_redemptions_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.redemptions
    ADD CONSTRAINT fk_redemptions_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: rewards fk_rewards_program_config; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rewards
    ADD CONSTRAINT fk_rewards_program_config FOREIGN KEY (program_config_id) REFERENCES public.program_config(id);


--
-- Name: rewards fk_rewards_tenant; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rewards
    ADD CONSTRAINT fk_rewards_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: points_movements fkn6gn6tu4ckon96haw5r93v0qy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_movements
    ADD CONSTRAINT fkn6gn6tu4ckon96haw5r93v0qy FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: purchase_transactions fkod88c9nume514hcadgvbqc6bl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_transactions
    ADD CONSTRAINT fkod88c9nume514hcadgvbqc6bl FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- PostgreSQL database dump complete
--

